spring:
  application:
    name: officer-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:finbank}
    username: ${POSTGRES_USER:finbank}
    password: ${POSTGRES_PASSWORD:finbank}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: health,info