spring:
  application:
    name: loan-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:finbank}
    username: ${POSTGRES_USER:finbank}
    password: ${POSTGRES_PASSWORD:finbank}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8088

finbank:
  services:
    transaction-url: http://localhost:8083

management:
  endpoints:
    web:
      exposure:
        include: health,info
