spring:
  application:
    name: loan-service
  datasource:
    url: jdbc:postgresql://localhost:5432/finbank
    username: finbank
    password: finbank
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8088

finbank:
  services:
    transaction-url: http://localhost:8083

management:
  endpoints:
    web:
      exposure:
        include: health,info
