spring:
  application:
    name: audit-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:finbank}
    username: ${POSTGRES_USER:finbank}
    password: ${POSTGRES_PASSWORD:finbank}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

server:
  port: 8091

management:
  endpoints:
    web:
      exposure:
        include: health,info
