spring:
  application:
    name: support-service
  datasource:
    url: jdbc:postgresql://localhost:5432/finbank
    username: finbank
    password: finbank
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
server:
  port: 8089
management:
  endpoints:
    web:
      exposure:
        include: health,info