package com.finbank.support.service;
import com.finbank.support.dto.*;import com.finbank.support.entity.*;import com.finbank.support.exception.SupportException;import com.finbank.support.repository.SupportTicketRepository;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.LocalDateTime;import java.util.*;import java.util.stream.Collectors;
@Service public class SupportServiceImpl implements SupportService{
 private final SupportTicketRepository repo;public SupportServiceImpl(SupportTicketRepository repo){this.repo=repo;}
 @Transactional public TicketResponse create(CreateTicketRequest r){SupportTicket t=new SupportTicket();t.setTicketReference("TKT"+UUID.randomUUID().toString().replace("-","").substring(0,19).toUpperCase());t.setCustomerNumber(r.customerNumber().trim().toUpperCase());t.setRequestType(r.requestType());t.setPriority(r.priority());t.setSubject(r.subject().trim());t.setDescription(r.description().trim());t.setStatus(SupportStatus.OPEN);return map(repo.save(t));}
 public TicketResponse get(String ref){return map(entity(ref));}
 public List<TicketResponse> customerTickets(String customer){return repo.findByCustomerNumberOrderByCreatedAtDesc(customer.trim().toUpperCase()).stream().map(this::map).toList();}
 public List<TicketResponse> byStatus(SupportStatus status){return repo.findByStatusOrderByCreatedAtAsc(status).stream().map(this::map).toList();}
 @Transactional public TicketResponse update(String ref,UpdateTicketRequest r){SupportTicket t=entity(ref);if(t.getStatus()==SupportStatus.CLOSED)throw new SupportException("Closed ticket cannot be updated");if(r.status()==SupportStatus.IN_PROGRESS&& (r.assignedOfficer()==null||r.assignedOfficer().isBlank()))throw new SupportException("Assigned officer is required");if(r.status()==SupportStatus.RESOLVED&&(r.resolution()==null||r.resolution().isBlank()))throw new SupportException("Resolution is required");t.setStatus(r.status());if(r.assignedOfficer()!=null&&!r.assignedOfficer().isBlank())t.setAssignedOfficer(r.assignedOfficer().trim());if(r.resolution()!=null&&!r.resolution().isBlank())t.setResolution(r.resolution().trim());return map(repo.save(t));}
 private SupportTicket entity(String ref){return repo.findByTicketReference(ref).orElseThrow(()->new SupportException("Support ticket not found"));}
 private TicketResponse map(SupportTicket t){return new TicketResponse(t.getTicketReference(),t.getCustomerNumber(),t.getRequestType(),t.getStatus(),t.getPriority(),t.getSubject(),t.getDescription(),t.getAssignedOfficer(),t.getResolution(),t.getCreatedAt(),t.getUpdatedAt());}
}